// Command couponindex builds the promo-code index artifact offline.
//
//	couponindex -engine hashjoin -out data/valid_coupons.txt data/couponbase1.gz data/couponbase2.gz data/couponbase3.gz
//	couponindex -engine duckdb   -out data/valid_coupons.txt data/couponbase*.gz
package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"time"

	"kart/internal/couponbuild"
	"kart/internal/promo"
)

func main() {
	engine := flag.String("engine", string(couponbuild.EngineHashJoin), "build engine: hashjoin | duckdb")
	out := flag.String("out", "data/valid_coupons.txt", "output index file")
	minSources := flag.Int("min-sources", 2, "a code must appear in at least this many files")
	tmpDir := flag.String("tmp", "", "temp dir for spill files (default: OS temp dir)")
	partitions := flag.Int("partitions", 0, "split the join into N hash partitions (hashjoin: on-disk buckets, default 64; duckdb: query passes, default 1)")
	memLimit := flag.String("memory-limit", "1GB", "duckdb: memory cap before spilling to disk")
	flag.Parse()

	log := slog.New(slog.NewTextHandler(os.Stderr, nil))
	if flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: couponindex [flags] file1.gz file2.gz ...")
		flag.PrintDefaults()
		os.Exit(2)
	}

	builder, err := couponbuild.New(couponbuild.Engine(*engine), couponbuild.Config{
		MinSources:  *minSources,
		TempDir:     *tmpDir,
		Partitions:  *partitions,
		MemoryLimit: *memLimit,
	})
	if err != nil {
		log.Error("invalid configuration", "err", err)
		os.Exit(2)
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	start := time.Now()
	codes, err := builder.Build(ctx, flag.Args())
	if err != nil {
		log.Error("build failed", "engine", *engine, "err", err)
		os.Exit(1)
	}

	names := make([]string, flag.NArg())
	for i, p := range flag.Args() {
		names[i] = filepath.Base(p)
	}
	header := fmt.Sprintf("Generated by cmd/couponindex (engine=%s) at %s\nRule: length %d-%d, present in >= %d of: %s\n%d valid codes",
		*engine, time.Now().UTC().Format(time.RFC3339), promo.MinLen, promo.MaxLen, *minSources, strings.Join(names, ", "), len(codes))

	// Write to a temp file and rename so a running server never reads a
	// half-written index.
	tmp := *out + ".tmp"
	f, err := os.Create(tmp)
	if err == nil {
		err = promo.WriteIndex(f, codes, header)
		if cerr := f.Close(); err == nil {
			err = cerr
		}
	}
	if err == nil {
		err = os.Rename(tmp, *out)
	}
	if err != nil {
		log.Error("write index failed", "err", err)
		os.Exit(1)
	}
	log.Info("index built", "engine", *engine, "codes", len(codes), "out", *out, "took", time.Since(start))
}
